### ISSUE TITLE
你好啊,我看见你想做游戏

### ISSUE THREAD

**Issue by 2439905184** [lightyears1998/a-gzhu-coder#12]
只不过我们用的引擎不一样,我用的是开源Godot 哈哈。
因为我不去给别人的公司打工写游戏,而是做类似独立游戏的小游戏。
未来有自研内部游戏引擎的想法但还不是现在。

**Comment by lightyears1998** [comment]
> 只不过我们用的引擎不一样,我用的是开源Godot 哈哈。 因为我不去给别人的公司打工写游戏,而是做类似独立游戏的小游戏。 未来有自研内部游戏引擎的想法但还不是现在。

Hello, @2439905184 小沙盒工作室室长。之前在 bilibili，贴吧和 godoter.cn 都看见过你。😊

其实我最近是在学习 Godot 啦。（这个 repo 是我本科期间的，其实有点历史了，所以上面的信息有点旧了。）Godot 确实挺好用的，尤其是4.0版本更新的 lambda 函数让写小回调函数方便了很多。GDScript 的新语法我也很喜欢。Vulkan Render 好像也很酷炫。不过，我没用过 Godot 的 3D 功能，听说 GD4 对 3D 做了很大的更新。未来可期呀。

PS. 最近我在用 Godot 开发一个自用的开源的时间管理软件 A Cycle。（其实我自己对这个软件的定位还并不清楚？）前端采用的是 Godot 4，后端采用的 Node.js + TypeScript。如果您有兴趣可以[看一看](https://github.com/lightyears1998/a-cycle)。目前还在开发早期阶段，大早期（画饼中）。大家用 Godot 写游戏，我用 Godot 做软件…… 可能是有点奇葩了。🤣用 Godot 的话，自己要造的轮子挺多，不过造轮子的过程也挺舒服的就是了。

**Comment by 2439905184** [comment]
我也用godot做过软件界面
做了个terasology的启动器
后端语言是nim
前端界面是godot
【terasology 可视化版本的启动器-哔哩哔哩】 https://b23.tv/ry7lwqE
缺点是图形化程序有点大。
毕竟这是个游戏引擎

**Comment by lightyears1998** [comment]
> 我也用godot做过软件界面 做了个terasology的启动器 后端语言是nim 前端界面是godot

Thanks! 我之前没有接触过 Nim，看起来它是一门有趣的新语言。有空的时候我会看看这个项目的 GitHub repo。😁

> 缺点是图形化程序有点大。毕竟这是个游戏引擎

Godot 导出的文件体积确实有点大，我之前试过用 GD 4.0 导出 Windows Desktop 平台，引擎本身要占 60 MB 左右。毕竟单纯 GUI 的话还要带上物理引擎一起导出实在有点臃肿了。自己编译导出模板，关掉不必要的功能也许可以缓解这个问题。虽然我还没有这样试过。

在 GD 4.0 版本 reduz 的一个 [PR](https://www.github.com/godotengine/godot/pull/62996) 里面实现了一个小工具，可以方便地创建 Engine Build Configuration。可以节约自行编译导出模板调配置时的一点时间。PR 下面有大佬做表格分析了 GD 各个模块占用的体积大小，猜测去掉没使用到的功能的话，引擎的体积也许可以压到 20MB 左右。

**Comment by 2439905184** [comment]
嗯

**Comment by 2439905184** [comment]
我自己编译过纯2d的导出模板，还是没小多少

**Comment by 2439905184** [comment]
用visual free basic 开发的图形化软件是128kb起步的，缺点就是用的是系统原生GUI，不太好看。

**Comment by 2439905184** [comment]
用aardio开发的window软件是1MB起步的

**Comment by 2439905184** [comment]
用electro的话是不是比godot导出还大

**Comment by lightyears1998** [comment]
> 用visual free basic 开发的图形化软件是128kb起步的，缺点就是用的是系统原生GUI，不太好看。
> 用aardio开发的window软件是1MB起步的

Nim 和 arrdio 都挺小众的呀。Visual Free Basic 竟然是一个人用五个月时间开发的，肃然起敬。arrdio 看起来挺好用的。Nim 的网站好像很有高级感。好像最近，矢量工坊宝儿姐那种传说中的人物在做 Nim 的文档翻译。

> 用electro的话是不是比godot导出还大

我有一个朋友在尝试用 Electorn + PIXI.js 做 RPG。Electron 导出要捎带上一个 Chromium 体积确实不比 Godot 小。

**Comment by 2439905184** [comment]
> > 用visual free basic 开发的图形化软件是128kb起步的，缺点就是用的是系统原生GUI，不太好看。
> > 用aardio开发的window软件是1MB起步的
> 
> Nim 和 arrdio 都挺小众的呀。Visual Free Basic 竟然是一个人用五个月时间开发的，肃然起敬。arrdio 看起来挺好用的。Nim 的网站好像很有高级感。好像最近，矢量工坊宝儿姐那种传说中的人物在做 Nim 的文档翻译。
> 
> > 用electro的话是不是比godot导出还大
> 
> 我有一个朋友在尝试用 Electorn + PIXI.js 做 RPG。Electron 导出要捎带上一个 Chromium 体积确实不比 Godot 小。

宝儿姐在国内的godot群里，我也在。之前矢量工坊的一个成员还加我好友，说想要做游戏加入我，但是后来他对我失望了，我能感觉到他给我的压力，而且他也确实很喜欢游戏，但是现实是社会是金钱社会，又要赚钱，就很矛盾。
我是学生。感觉不和他交流了也挺不错的，我其实不能承受压力。我会很容易焦虑，影响睡觉和精力。
还是一个人作游戏，做开源比较爽，唯一缺点是劳动力低下开发周期长。
我那个path-tool是我在中秋节开发的。但是中秋节只有三天，我想在三天之内写完它。所以半夜两点还在写代码。（但是我真的很想睡觉）

**Comment by lightyears1998** [comment]
我觉得个人开发者其实挺好的。我现在也还是学生，不过后年马上就要毕业了。如果要靠做游戏挣钱，而且时间比较紧，就不应该选择 Godot，而是该学习市面上广泛使用的引擎。换言之，选择 Godot 似乎就不应该以短时间内开发出能挣钱的游戏作为目标。我觉得个人开发者，完全可以按照自己舒适的节奏来开发。想写就写，累了就休息，压力似乎大可不必。我个人觉得，我们独立开发者能讲好自己想表达的故事就算是大成功了。我学习 Godot 是希望能用它便利地表达自己的一些想法，未来要谋生的话，还需要另找一份程序员的工作。（希望加班少一点，能让我有时间整点兴趣活动。）只是……我中间拐了个弯就开始用 Godot 写软件了，游戏倒是没有开始做。🤣

Godot 国内的圈子比较小，在各大平台上很容易看见熟人。有时候逛着逛着就会发现一个 ID 眼熟。通过欣赏他人的作品我还是学到了不少东西。开发周期长一点也无所谓啦，反正都是愉快的过程。愉快的过程长一点也挺好的。玩 Godot 能认识许多有趣的人。比如，Reduz 我原本以为他是美国人，结果点进他的 Profile 一看才知道他来自阿根廷；我最近看的 godot-sqlite 的项目，repo 主是克罗地亚人，我们中间隔了 8 小时左右的时差。那个克罗地亚小哥还贼喜欢用 emoji。😂

打磨一件作品真的急不得。那个蜜汁软件 A Cycle 我原本想几天就写完，毕竟我的导师也在催我干活了，不过最后还是折腾了一个多星期。直到现在才算是有了一点眉目。未来的开发周期估计还很长。所以我觉得做 Godot 真的急不来，按照自己的节奏放轻松就好了。来日方长，要保持良好的作息才有长期的生产力。

**Comment by 2439905184** [comment]
好
